name: Deploy MkDocs with Robot Logs

on:
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - main  # Adjust based on your default branch
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 2 AM (adjust as needed)

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout MkDocs Repository
        uses: actions/checkout@v4

      - name: Download Robot Framework Logs from Test Repo
        run: |
          mkdir -p docs/logs  # Ensure logs directory exists
          gh run download -R username/test-repo -n robot-test-results -D docs/logs
        env:
          GH_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}  # Use a PAT if needed

      - name: Install Dependencies
        run: pip install mkdocs mkdocs-material  # Add any plugins if needed

      - name: Build MkDocs Site
        run: mkdocs build --clean

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: robot-logs  # Change to your project name
          directory: site
          apiToken: ${{ secrets.CF_API_TOKEN }}
