name: Build and Deploy MkDocs with Robot Reports

on:
  workflow_run:
    workflows: ["Robot Framework Tests"]  # Name of the workflow in the test repo
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout MkDocs Code
        uses: actions/checkout@v3

      - name: Download Robot Framework Reports
        uses: actions/download-artifact@v3
        with:
          name: robot-reports
          path: docs/reports/
          repository: sinesipho-jacobs/test-workflow  # Replace with your test repo
          run-id: ${{ github.event.workflow_run.id }}

      - name: Inject Build Number
        run: |
          echo "Build Number: ${{ github.event.workflow_run.id }}" >> docs/reports.md

      - name: Build MkDocs Site
        run: mkdocs build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: robot-logs
          directory: site/
