site_name: Robot Framework Logs
theme:
  name: material

nav:
  - Home: index.md
  - Test Reports:
      - Latest Report: latest/log.html
      - Build 368: 368/log.html
      - Build 367: 367/log.html
      - Build 366: 366/log.html
      - Build 365: 365/log.html
      - Build 364: 364/log.html
      - Build 363: 363/log.html
      - Build 362: 362/log.html
      - Build 361: 361/log.html
      - Build 358: 358/log.html
      - Build 357: 357/log.html
