name = "robot-logs"

account_id = "15b0ccd4c68c56b4231b01eb799d53e8"
workers_dev = true  # Set this to false if deploying to a production environment
compatibility_flags = []

compatibility_date = "2025-03-17"

[build]
command = "mkdocs build"  # Build the site using MkDocs.
directory = "site"         # The default output directory for MkDocs is 'site'.

[pages]
pages_build_output_dir = "site"