
name: Deploy MkDocs to Cloudflare Pages

on:
  push:
    branches:
      - main  # Adjust based on your workflow
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout MkDocs Repository
        uses: actions/checkout@v4

      - name: Checkout Test Workflow Repository (Robot Logs)
        uses: actions/checkout@v4
        with:
          repository: sinesipho-jacobs/test-workflow
          path: test-workflow

      - name: Debug Checkout
        run: ls -lah test-workflow

      - name: Debug Checkout
        run: ls -lah test-workflow/webapp_tests
        
      - name: Debug Checkout
        run: ls -lah test-workflow/webapp_tests/api

      - name: Find and Merge Robot Framework logs
        run: |
          mkdir -p merged-results/
          find test-workflow/webapp_tests -name "*.xml" -exec mv {} ./merged-results/ \;

          OUTPUT_FILES=$(find ./merged-results -name "output.xml" | tr '\n' ' ')
          if [ -n "$OUTPUT_FILES" ]; then
            echo "Merging output files: $OUTPUT_FILES"
            rebot --output ./merged-results/output.xml --log ./merged-results/log.html --report ./merged-results/report.html $OUTPUT_FILES
          else
            echo "No output.xml files found. Skipping merging."
            exit 1
          fi
          
      - name: "⬆️ Upload Merged Test Results"
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: merged-robot-logs
          path: |
            merged-results/output.xml
            merged-results/log.html
            merged-results/report.html


          
      - name: Append Build Number to Reports Page
        run: |
          echo "## Test Reports" > docs/reports.md
          echo "- [Latest Logs (Build $GITHUB_RUN_NUMBER)](merged-results/log.html)" >> docs/reports.md
          
      - name: Install MkDocs
        run: pip install -r requirements.txt
        # run: pip install mkdocs

      - name: Build MkDocs Site
        run: mkdocs build --strict

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          projectName: robot-logs  # Adjust to your Cloudflare Pages project name
          directory: site  # MkDocs output directory
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
